# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  AI:
    Providers:
      OpenAI:
        #[password]
        APIKey: ${decrypt:}
        BaseUrl: ""
        # The default model, if not explicitly specified on the calling Agent.
        #
        # See dev.langchain4j.model.openai.OpenAiChatModelName for the list of all supported models
        # [enum: gpt-4o, gpt-4.1, gpt-4.1-mini, gpt-4.1-nano, gpt-5]
        DefaultModel: ""
        # The default embedding model, if not explicitly specified.
        #
        # [enum: text-embedding-3-small, text-embedding-3-large, text-embedding-ada-002]
        DefaultEmbeddingModel: ""
