# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/rest-clients-1.json
RestClients:
  langChain:
    Url: https://api.openai.com
    Properties:
      SensitiveData: true
